platform :ios, '7.0'
pod 'AFNetworking'
pod 'AMap2DMap'
pod 'FMDB'
pod 'IQKeyboardManager'
pod 'JSONModel'
pod 'libextobjc'
pod 'MCUIColorUtils'
pod 'NSDictionary+Accessors'
pod 'UIActionSheet+Blocks'
pod 'UIAlertView+Block'
pod 'UMengAnalytics'
